(define (strong-password-checker-fold-run L rep c0 c1)
  (if (>= L 3)
      (let ((m (modulo L 3)))
        (values (+ rep (quotient L 3))
                (if (= m 0) (+ c0 1) c0)
                (if (= m 1) (+ c1 1) c1)))
      (values rep c0 c1)))

(define (strong-password-checker-kernel password)
  (let ((n (string-length password)))
    (let loop ((i 0) (low 0) (up 0) (dig 0) (rep 0) (c0 0) (c1 0) (cur #f) (len 0))
      (if (< i n)
          (let* ((c (string-ref password i))
                 (low2 (if (char-lower-case? c) 1 low))
                 (up2 (if (char-upper-case? c) 1 up))
                 (dig2 (if (char-numeric? c) 1 dig)))
            (if (and (char? cur) (char=? c cur))
                (loop (+ i 1) low2 up2 dig2 rep c0 c1 cur (+ len 1))
                (let-values (((rep2 c02 c12) (strong-password-checker-fold-run len rep c0 c1)))
                  (loop (+ i 1) low2 up2 dig2 rep2 c02 c12 c 1))))
          (let-values (((rep2 c02 c12) (strong-password-checker-fold-run len rep c0 c1)))
            (let ((missing (- 3 (+ low up dig))))
              (cond
                ((< n 6) (max missing (- 6 n)))
                ((<= n 20) (max missing rep2))
                (else
                 (let* ((del (- n 20))
                        (s1 (min c02 del))
                        (del1 (- del s1))
                        (rep3 (- rep2 s1))
                        (s2 (min c12 (quotient del1 2)))
                        (del2 (- del1 (* 2 s2)))
                        (rep4 (- rep3 s2))
                        (s3 (min (quotient del2 3) rep4))
                        (rep5 (- rep4 s3)))
                   (+ (- n 20) (max missing rep5)))))))))))

(define (strong-password-checker password)
  (strong-password-checker-kernel password))
