(require racket/unsafe/ops)

(define (kernel-2035 nums)
  (define n (unsafe-fxrshift (length nums) 1))
  (define m (unsafe-fxlshift 1 n))
  (define vs (list->vector nums))
  (define total (for/sum ([x (in-vector vs)]) x))
  (define size (make-vector (add1 n) 1))
  (let fill ([k 0] [c 1])
    (when (<= k n)
      (vector-set! size k c)
      (fill (add1 k) (quotient (* c (- n k)) (add1 k)))))
  (define (build start)
    (define items (make-vector n 0))
    (for ([i (in-range n)])
      (unsafe-vector-set! items i (unsafe-vector-ref vs (unsafe-fx+ start i))))
    (define sums (make-vector m 0))
    (define pc (make-vector m 0))
    (define cur (make-vector (add1 n) 0))
    (define buckets (make-vector (add1 n)))
    (for ([k (in-range (add1 n))])
      (unsafe-vector-set! buckets k (make-vector (unsafe-vector-ref size k) 0)))
    (unsafe-vector-set! cur 0 1)
    (let scan ([mask 1])
      (when (unsafe-fx< mask m)
        (define low (unsafe-fxand mask (unsafe-fx- 0 mask)))
        (define s (unsafe-fx+ (unsafe-vector-ref sums (unsafe-fx- mask low))
                              (unsafe-vector-ref items (unsafe-fx- (integer-length low) 1))))
        (define k (unsafe-fx+ (unsafe-vector-ref pc (unsafe-fxrshift mask 1)) (unsafe-fxand mask 1)))
        (unsafe-vector-set! sums mask s)
        (unsafe-vector-set! pc mask k)
        (define b (unsafe-vector-ref buckets k))
        (define c (unsafe-vector-ref cur k))
        (unsafe-vector-set! b c s)
        (unsafe-vector-set! cur k (unsafe-fx+ c 1))
        (scan (unsafe-fx+ mask 1))))
    buckets)
  (define L (build 0))
  (define R (build n))
  (for ([k (in-range (add1 n))])
    (vector-sort! (unsafe-vector-ref R k) <))
  (define best +inf.0)
  (for ([k (in-range (add1 n))])
    (define rv (unsafe-vector-ref R (unsafe-fx- n k)))
    (define len (unsafe-vector-length rv))
    (define lv (unsafe-vector-ref L k))
    (define llen (unsafe-vector-length lv))
    (let scan ([i 0])
      (when (unsafe-fx< i llen)
        (define sL (unsafe-vector-ref lv i))
        (define T (unsafe-fx- total (unsafe-fxlshift sL 1)))
        (define idx (let probe ([lo 0] [hi len])
                      (if (unsafe-fx= lo hi)
                          lo
                          (let ([mid (unsafe-fxrshift (unsafe-fx+ lo hi) 1)])
                            (if (unsafe-fx<= (unsafe-fxlshift (unsafe-vector-ref rv mid) 1) T)
                                (probe (unsafe-fx+ mid 1) hi)
                                (probe lo mid))))))
        (when (unsafe-fx< idx len)
          (define d (abs (unsafe-fx- T (unsafe-fxlshift (unsafe-vector-ref rv idx) 1))))
          (when (< d best) (set! best d)))
        (when (unsafe-fx> idx 0)
          (define d (abs (unsafe-fx- T (unsafe-fxlshift (unsafe-vector-ref rv (unsafe-fx- idx 1)) 1))))
          (when (< d best) (set! best d)))
        (scan (unsafe-fx+ i 1)))))
  (exact-round best))

(define/contract (minimum-difference nums)
  (-> (listof exact-integer?) exact-integer?)
  (kernel-2035 nums))

(define/contract (minimumDifference nums)
  (-> (listof exact-integer?) exact-integer?)
  (kernel-2035 nums))
